#!/usr/bin/env python3
"""Fetch the self-hosted fonts into web/public/assets/fonts.

Backhog loads nothing from CDNs — the pixel face ships in the nginx image
like every other asset. Silkscreen is the console label face: labels,
keycaps, numbers. Prose stays on the system stack, which costs no bytes
and is present everywhere.

    python3 scripts/fetch-fonts.py
"""

import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "web", "public", "assets", "fonts")
CSS = os.path.join(ROOT, "web", "src", "pixel", "fonts.css")

FONTS = {
    # (family, weight, style) -> source file in google/fonts
    ("Silkscreen", 400, "normal"): "Silkscreen-Regular.ttf",
    ("Silkscreen", 700, "normal"): "Silkscreen-Bold.ttf",
}
BASE = "https://github.com/google/fonts/raw/main/ofl/silkscreen"


def main():
    os.makedirs(OUT, exist_ok=True)
    css = ["/* Generated by scripts/fetch-fonts.py — do not edit. */"]
    for (family, weight, style), name in sorted(FONTS.items()):
        dst = os.path.join(OUT, name.lower())
        urllib.request.urlretrieve(f"{BASE}/{name}", dst)
        size = os.path.getsize(dst)
        print(f"  {name.lower()}  {size // 1024}KB")
        css.append(f"""
@font-face {{
    font-family: "{family}";
    font-style: {style};
    font-weight: {weight};
    font-display: swap;
    src: url("/assets/fonts/{name.lower()}") format("truetype");
}}""")
    with open(CSS, "w") as f:
        f.write("\n".join(css) + "\n")
    print(f"wrote {os.path.relpath(CSS, ROOT)}")


if __name__ == "__main__":
    main()
