#!/usr/bin/env python3
"""Regenerate web/src/lib/gameicons.ts from game-icons.net.

Backhog uses two icon systems. The arcade sheet's pixel sprites carry the
hero marks; these vectors carry everything that must be small or must take
a colour — every affordance in the chrome, and the small nouns (trophy,
dice, hourglass) that would mush at 16px as pixel art. They replace
lucide-react entirely: one system, one attribution file.

The upstream SVGs are a black background rect plus a white glyph path. We
keep only the glyph geometry — the `d` strings — so the shipped module is
pure path data with no markup to inject, and the rendered icon inherits
`currentColor`.

    python3 scripts/fetch-gameicons.py

Icons are CC BY 3.0; the per-icon author is recorded alongside the path so
ATTRIBUTIONS.md can be checked against what actually ships.
"""

import os
import re
import sys
import urllib.request

BASE = "https://raw.githubusercontent.com/game-icons/icons/master"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "web", "src", "lib", "gameicons.ts")

# backhog name -> upstream author/icon. Names follow the lucide icons they
# replaced (kevron-down, trash, x, ...) so call sites read naturally.
ICONS = {
    # chrome affordances
    "arrow-left":    "delapouite/previous-button",
    "check":         "delapouite/check-mark",
    "check-circle":  "delapouite/check-mark",
    "chevron-down":  "badges/arrow-down",
    "chevron-up":    "badges/arrow-up",
    "chevrons-down": "badges/arrow-down",
    "chevrons-up":   "badges/arrow-up",
    "download":      "delapouite/cloud-download",
    "external-link": "delapouite/window",
    "grab":          "lorc/grab",
    "layout-grid":   "delapouite/window-bars",
    "log-out":       "delapouite/exit-door",
    "pencil":        "delapouite/pencil",
    "plus":          "badges/plus",
    "refresh":       "delapouite/clockwise-rotation",
    "rows":          "delapouite/hamburger-menu",
    "search":        "lorc/magnifying-glass",
    "settings":      "lorc/gears",
    "sliders":       "delapouite/settings-knobs",
    "trash":         "delapouite/trash-can",
    "x":             "badges/multiply",
    "lock":          "lorc/padlock",
    "hand":          "lorc/hand",
    # nouns
    "brush":         "delapouite/paint-brush",
    "broom":         "delapouite/broom",
    "bubbles":       "lorc/bubbles",
    "building":      "badges/building",
    "calendar":      "delapouite/calendar",
    "circle-dashed": "badges/blank",
    "clock":         "lorc/stopwatch",
    "timer":         "lorc/stopwatch",
    "dices":         "delapouite/rolling-dices",
    "door-open":     "lorc/doorway",
    "droplet":       "lorc/drop",
    "film":          "delapouite/film-strip",
    "flag":          "delapouite/checkered-flag",
    "gamepad":       "delapouite/gamepad",
    "gauge":         "delapouite/speedometer",
    "gas-mask":      "lorc/gas-mask",
    "gift":          "delapouite/present",
    "hammer-drop":   "lorc/hammer-drop",
    "history":       "lorc/clockwork",
    "hourglass":     "lorc/hourglass",
    "joystick":      "delapouite/joystick",
    "layers":        "lorc/cubes",
    "lifebuoy":      "delapouite/buoy",
    "list-checks":   "delapouite/checklist",
    "list-ordered":  "lorc/journey",
    "list-tree":     "lorc/checkbox-tree",
    "meteor-impact": "lorc/meteor-impact",
    "minus":         "badges/minus",
    "monitor":       "delapouite/game-console",
    "mountain":      "lorc/mountains",
    "play":          "guard13007/play-button",
    "shovel":        "lorc/spade",
    "small-fire":    "lorc/small-fire",
    "sparkles":      "delapouite/sparkles",
    "star":          "badges/star",
    "swords":        "lorc/crossed-swords",
    "tags":          "delapouite/price-tag",
    "target":        "lorc/targeting",
    "tooth":         "lorc/tooth",
    "trophy":        "lorc/trophy",
    "tv":            "delapouite/tv",
    "wooden-door":   "lorc/wooden-door",
    "zap":           "lorc/focused-lightning",
    # statuses
    "ban":           "lorc/interdiction",
    "x-circle":      "lorc/interdiction",
}

# The 512x512 background rect every upstream icon opens with.
BACKDROP = re.compile(r"^M0 0h512v512H0z$")
PATH_D = re.compile(r"<path[^>]*\sd=\"([^\"]+)\"")


def fetch(slug):
    with urllib.request.urlopen(f"{BASE}/{slug}.svg", timeout=20) as r:
        return r.read().decode("utf-8")


def glyph(svg, slug):
    paths = [d for d in PATH_D.findall(svg) if not BACKDROP.match(d.strip())]
    if not paths:
        sys.exit(f"{slug}: no glyph path found")
    return paths


def main():
    icons, credits = {}, {}
    for name, slug in sorted(ICONS.items()):
        icons[name] = glyph(fetch(slug), slug)
        credits[name] = slug
        print(f"  {name:14s} <- {slug}")

    def js_obj(d, fmt):
        rows = ",\n".join(f'  "{k}": {fmt(v)}' for k, v in d.items())
        return "{\n" + rows + ",\n}"

    body = f"""// Generated by scripts/fetch-gameicons.py — do not edit by hand.
//
// Glyph geometry from game-icons.net (CC BY 3.0), by the authors named in
// CREDITS below. Only the path data ships: the <Gi> component builds the
// <svg> around it, so every icon inherits currentColor and stays crisp at
// any size.

/** name -> array of SVG path `d` strings, on a 0 0 512 512 viewBox. */
export const GAME_ICONS = Object.freeze({js_obj(icons, lambda v: "[" + ", ".join(f'"{p}"' for p in v) + "]")});

/** name -> "author/icon" upstream, for attribution. */
export const CREDITS = Object.freeze({js_obj(credits, lambda v: f'"{v}"')});

/** Every valid icon name. */
export type GiName = keyof typeof GAME_ICONS;
"""
    open(OUT, "w").write(body)
    size = os.path.getsize(OUT)
    print(f"\nwrote {OUT} ({size // 1024}KB, {len(icons)} icons)")


if __name__ == "__main__":
    main()
