import type { GiName } from "@/lib/gameicons";

/**
 * Icon key come from the backend catalogue (internal/achievements); unknown
 * keys fall back to the trophy so a new achievement still renders.
 */
const ICONS: Record<string, GiName> = {
  droplet: "droplet",
  brush: "brush",
  "broom": "broom",
  "bubbles": "bubbles",
  "gas-mask": "gas-mask",
  "small-fire": "small-fire",
  "chevrons-down": "chevrons-down",
  "hammer-drop": "hammer-drop",
  tooth: "tooth",
  "meteor-impact": "meteor-impact",
  "wooden-door": "wooden-door",
  minus: "minus",
  shovel: "shovel",
  timer: "timer",
  mountain: "mountain",
  target: "target",
  "door-open": "door-open",
  hourglass: "hourglass",
  amphora: "amphora",
  "mayan-pyramid": "mayan-pyramid",
  "stone-tablet": "stone-tablet",
  "time-trap": "time-trap",
  "vintage-robot": "vintage-robot",
  fossil: "fossil",
  "lightning-storm": "lightning-storm",
  bookshelf: "bookshelf",
  hand: "hand",
  swords: "swords",
  gift: "gift",
  "x-circle": "x-circle",
  ban: "ban",
  refresh: "refresh",
  history: "history",
  flag: "flag",
  dices: "dices",
  sparkles: "sparkles",
  star: "star",
  calendar: "calendar",
  layers: "layers",
  "check-circle": "check-circle",
  play: "play",
  check: "check",
  zap: "zap",
  clock: "clock",
  gauge: "gauge",
  "chevrons-up": "chevrons-up",
  joystick: "joystick",
  "list-checks": "list-checks",
  // The series mastery ladder.
  "book-pile": "book-pile",
  "linked-rings": "linked-rings",
  "scroll-unfurled": "scroll-unfurled",
  "imperial-crown": "imperial-crown",
  sprint: "sprint",
  cycle: "cycle",
  "full-folder": "full-folder",
  // The diversity and platform mastery ladder.
  "pizza-slice": "pizza-slice",
  compass: "compass",
  "dust-cloud": "dust-cloud",
  "family-tree": "family-tree",
  "cuckoo-clock": "cuckoo-clock",
  "mushroom-gills": "mushroom-gills",
  gamepad: "gamepad",
  knapsack: "knapsack",
  footprint: "footprint",
  clover: "clover",
  // The easter eggs.
  "night-sleep": "night-sleep",
  eyeball: "eyeball",
  keyboard: "keyboard",
  whirlwind: "whirlwind",
  // The books arena; the rest of its icons reuse the games keys above.
  building: "building",
  headphones: "headphones",
  sliders: "sliders",
  camera: "camera",
  // The generic glyph a locked hidden achievement is masked with.
  lock: "lock",
};

export function achievementIcon(key: string): GiName {
  return ICONS[key] ?? "trophy";
}
